import { Loader } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import { Leva } from "leva";
import Head from "next/head";
import Modal from "../components/Modal";
import Scene from "../components/Scene";
import SideModal from "../components/SideModal";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pictures from my camera</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Loader />
      <main className="w-[100vw] h-[100vh] overflow-hidden">
        <Modal />
        <SideModal />
        <h1 className="font-extrabold text-4xl ml-2 title absolute z-50 top-[-5vh] opacity-0">
          pictures from my camera
          <p className="text-base">a three js experiment</p>
          <p className="text-base">made by yoan saint juste</p>
        </h1>
        <p className="clickOnCamera absolute z-50 bottom-3 text-center w-full opacity-0">
          - click on the camera -
        </p>
        <Canvas camera={{ position: [80, 62, 77] }}>
          <Scene />
        </Canvas>
        <Leva hidden />
      </main>
    </div>
  );
}
